fashion/fashion/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from fashionrecommender import views

urlpatterns = [
    path('', views.index),
    path('fashion/', include('fashionrecommender.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fashion/fashionrecommender/urls.py
from django.urls import path

from . import views

app_name = 'fashion'

urlpatterns = [
    path('', views.index, name='index'),
    path('capture', views.capture, name='capture'),
    path('upload', views.upload, name='upload'),
    path('runmodel', views.runmodel, name='runmodel'),
    path('search', views.search, name='search'),
    path('showsimilar', views.showsimilar, name='showsimilar'),
    path('lazyload', views.lazyload, name='lazyload'),
]

fashion/fashionrecommender/models.py
from django.db import models

# Create your models here.

fashion/fashionrecommender/views.py
from django.shortcuts import render
from django.views.decorators import gzip
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
import cv2
import os
import subprocess
import requests

def index(request):
    return render(request, 'fashion/index.html')


def capture(request):
    filename = use_webcam()
    context = {'success': True,
               'message': 'Capture Success', 'imageList': [filename]}
    return render(request, 'fashion/index.html', context)


def use_webcam():
    camera = cv2.VideoCapture(0)
    cv2.namedWindow("Fashion Detector")
    ret, frame = camera.read()
    cv2.imshow("Fashion Detector", frame)
    fs = FileSystemStorage()
    filePath = os.path.dirname(__file__)
    dirPath = os.path.abspath(os.path.dirname(filePath))
    newDirPath = os.path.join(dirPath, 'media')
    img_name = "fashion-capture.jpg"
    if ret == True:
        cv2.imwrite(os.path.join(newDirPath, img_name), frame)
        uploaded_file_url = fs.url(img_name)
    camera.release()
    cv2.destroyAllWindows()
    return uploaded_file_url


def upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        myfile.name = "fashion-upload.jpg"
        if(fs.exists(myfile.name)):
            fs.delete(myfile.name)
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'fashion/index.html', {
            'success': True,
            'message': 'Upload Success',
            'imageList': [uploaded_file_url]
        })
    return render(request, 'fashion/index.html')


def runmodel(request):
    subProcess = subprocess.Popen("spark-submit --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11 .\predict.py", shell=True)
    subProcess.wait()
    predictResult =[]
    if(subProcess.returncode == 0):
        f = open("predict_output.txt", "r")
        for line in f.read().split("\n"):
            predictResult.append(line)
        context = {'success': True,
               'message': 'Predicted Successfully!', 'modal': True, 'predictResult': predictResult}
    else:
        context = {'success': True,
               'message': 'Failed! Retry Again', 'modal': True, 'predictResult': predictResult}
    
    return render(request, 'fashion/index.html', context)

def search(request):
    search = request.POST.get('search')
    params = {'q': search, 'size': '10', 'scroll': '1m'}
    context = searchElasticCluster("_search", params)
    return render(request, 'fashion/search.html', context)

def showsimilar(request):
    masterCategoryList = []
    subCategoryList = []
    articleTypeList = []
    f = open("predict_output.txt", "r")
    for line in f.read().split("\n"):
        if line != "":
            splitString = line.split('=')[1]
            masterCategory, subCategory, articleType = splitString.split('_')
            masterCategoryList.append(masterCategory.strip())
            subCategoryList.append(subCategory.strip())
            articleTypeList.append(articleType.strip())
    params = {'q': articleTypeList, 'size': '10', 'scroll': '1m'}
    context = searchElasticCluster("_search", params)
    return render(request, 'fashion/search.html', context)

    
def searchElasticCluster(type, params):
    try:
        lazyLoad = False
        if type == "_search/scroll":
            lazyLoad = True
        response = requests.get("http://localhost:9200/"+type, params)
        if response.status_code == 200:
            data = response.json()
            resultArray = []
            for hit in data['hits']['hits']:
                resultArray.append(hit['_source'])
            message = "Search Success"
            showAlert = True
            scrollId = data['_scroll_id']
            context = {'search': resultArray, 'message':message, 'success': showAlert, 'scrollId': scrollId, 'lazyLoad': lazyLoad}
            return context
        else:
            message = "Search Failed"
            showAlert = True
            context = {'message': message, 'success': showAlert}
            return context
    except:
        message = "No Elastic Cluster Found"
        showAlert = True
        context = {'message': message, 'success': showAlert}
        return context

def lazyload(request):
    scrollid = request.POST.get('scrollid')
    params = {'scroll_id': scrollid, 'scroll': '1m'}
    context = searchElasticCluster("_search/scroll", params)
    return render(request, 'fashion/search.html', context)

fashion/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SparkFab</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-between"
    >
      <h3 class="display-4 text-white">SparkFab</h3>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <form action={% url 'fashion:search' %} class="form-inline my-2 my-lg-0" id="search-form" method="POST">
        {% csrf_token %}
        <input
          class="form-control mr-sm-2"
          type="search"
          placeholder="Search"
          name="search"
          id="search"
          required
        />
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

fashion/templates/fashion/index.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<script>
   loadSpinner = (param) => {
     document.getElementById("result-row").innerHTML = `<div class="spinner-grow text-primary" style="width: 5rem; height:5rem" role="status"><span class="sr-only">Loading...</span></div><br /><h5>${param}</h5>`
   }
</script>
{% if success %}
<script>
  setTimeout(()=> {
    $(".alert").alert('close')
  }, 5000)
</script>
<div class="row mt-3 mb-3">
  <div class="col-12 m-auto alert alert-success" role="alert">
    {{message}}
  </div>
</div>
{% endif %}
<div class="row">
<div class="col-md-6 m-auto">
    <div class="card mb-3 mt-3">
        <div class="card-body">
          <h5 class="card-title">Live Fashion</h5>
          <p class="card-text">
            Click below button to allow webcam to capture image
          </p>
          <p class="card-text">
            <a class="btn btn-outline-dark" href={% url 'fashion:capture' %}>Capture</a>
          </p>
        </div>
      </div>
</div>
<div class="col-md-6 m-auto">
    <div class="card mb-3 mt-3">
        <div class="card-body">
          <h5 class="card-title">Upload Fashion</h5>
          <p class="card-text">
            Click below button to upload image
          </p>
          <form action={% url 'fashion:upload' %} method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="custom-file col-8 ml-2 mr-2">
                <input type="file" name="myfile" class="custom-file-input" id="validatedCustomFile" />
                <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
            </div>
            <button type="submit" class="btn btn-outline-dark col-2 mr-2">Submit</button>
            </div>
        </form>
        </div>
      </div>
</div>
</div>
{% if success %}
<div class="row mt-3 mb-3">
<!-- Button trigger modal -->
<div class="col-12 mt-2 mb-2">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#imageModal">
    View Images
  </button>
  <a onclick="loadSpinner('Model Predicting ...')" class="btn btn-primary" href={% url 'fashion:runmodel' %}>
    Predict Images
  </a>
</div>
<div class="container m-auto" id="result-row"></div>
{% if modal %}
<div class="col-12 mt-4 mb-4">
<h3>Prediction Results</h3>
<div class="container">
{% for image in predictResult %}
<ul>
  {{image}}
</ul>
{% endfor %}
</div>
<a onclick="loadSpinner('Loading Items ...')" class="btn btn-primary" href={% url 'fashion:showsimilar' %}>
  Show Similar Items
</a>
</div>
{% endif %}
<!-- Modal -->
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageModalLabel">Fashion Gallery</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for image in imageList %}
        <img src={{image}} class="img-fluid" />
        {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>
{% endif %}
{% endblock %}

fashion/templates/fashion/search.html
{% extends 'base.html' %} {% block content %} {% if success %}
<script>
  setTimeout(() => {
    $('.alert').alert('close');
  }, 5000);
</script>
<div class="row mt-3 mb-3">
  <div class="col-12 m-auto alert alert-success" role="alert">
    {{message}}
  </div>
</div>
{% endif %}
<div class="container d-flex mt-4 mb-4 justify-content-between">
  <a href={%url 'fashion:index' %} class="btn btn-outline-dark">Back</a>
  <form action={% url 'fashion:lazyload' %} class="form-inline my-2 my-lg-0" id="lazy-form" method="POST">
    {% csrf_token %}
  <input type="hidden" name="scrollid" value={{scrollId}} />
  <button type="submit" class="btn btn-outline-dark">Load More</button>
  </form>
</div>
<div class="row mt-4 mb-4">
{% if search|length > 0 %}
{% for data in search %}
    <div class="col-sm-6 mb-2" id={{data.id}} >
      <div class="card" style="flex-direction: row;">
        <div class="col-6">
            <img class="card-img-top" src={{data.link}} alt="SparkFab">
        </div>
        <div class="col-6 card-body">
          <h5 class="card-title text-center"> {{data.productDisplayName}} </h5>
          <div class="container text-center">
            <p class="card-text mb-2">{{data.masterCategory}} - {{data.subCategory}} </p>
            <p class="card-text mb-2">
                <span class="badge badge-pill badge-dark">{{data.gender}}</span>
                <span class="badge badge-pill badge-dark">{{data.articleType}}</span>
                <span class="badge badge-pill badge-dark">{{data.baseColour}}</span>
                <span class="badge badge-pill badge-dark">{{data.usage}}</span>
            </p>
            <a href="#" class="btn btn-primary mt-4 mb-2">Buy Now</a>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
{% endif %}
</div>
{% endblock %}